[package]
name = "nfctl-k8s"
description = "Kubernetes adapter for nfctl (implements ClusterPort)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nfctl-core.workspace = true

[lints]
workspace = true
