[package]
name = "nfctl-cli"
description = "nfctl: a CLI for operating Numaflow pipelines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "nfctl"
path = "src/main.rs"

[dependencies]
nfctl-core.workspace = true
nfctl-k8s.workspace = true
nfctl-graph.workspace = true
clap.workspace = true
clap_complete.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng = "0.10"
time.workspace = true
tokio.workspace = true
unicode-width = "0.2"
terminal_size = "0.4"

[dev-dependencies]
nfctl-core = { workspace = true, features = ["fake"] }
insta.workspace = true
assert_cmd.workspace = true
predicates = "3"

[lints]
workspace = true
